# Generated by Django 4.2.27 on 2025-12-28 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_date', models.DateField()),
                ('odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('gallons', models.DecimalField(decimal_places=3, max_digits=7)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vendor', models.CharField(blank=True, max_length=120)),
                ('fuel_type', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fuel_logs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_logs', to='tenants.tenant')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_logs', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-fuel_date', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'fuel_date'], name='fuel_fuello_tenant__f91190_idx'), models.Index(fields=['tenant', 'vehicle'], name='fuel_fuello_tenant__86d8bf_idx')],
            },
        ),
    ]
