# Generated by Django 4.2.27 on 2025-12-29 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('insurance', 'Insurance'), ('registration', 'Registration'), ('title', 'Title'), ('warranty', 'Warranty'), ('other', 'Other')], default='other', max_length=30)),
                ('title', models.CharField(blank=True, max_length=140)),
                ('file', models.FileField(upload_to='vehicle_docs/%Y/%m/')),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_documents', to='tenants.tenant')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['tenant', 'vehicle'], name='documents_v_tenant__91ec43_idx'), models.Index(fields=['tenant', 'doc_type'], name='documents_v_tenant__1090b3_idx'), models.Index(fields=['tenant', 'expires_on'], name='documents_v_tenant__711e36_idx')],
            },
        ),
    ]
