# Generated by Django 4.2.27 on 2025-12-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='default_inspection_due_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='tenant',
            name='inspection_alert_days_before',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='tenant',
            name='maintenance_alert_days_before',
            field=models.PositiveIntegerField(default=14),
        ),
        migrations.AddField(
            model_name='tenant',
            name='maintenance_alert_miles_before',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AddField(
            model_name='tenant',
            name='units_distance',
            field=models.CharField(choices=[('miles', 'Miles'), ('km', 'Kilometers')], default='miles', max_length=10),
        ),
        migrations.AddField(
            model_name='tenant',
            name='units_fuel',
            field=models.CharField(choices=[('gallons', 'Gallons'), ('liters', 'Liters')], default='gallons', max_length=10),
        ),
    ]
