# Generated by Django 4.2.27 on 2025-12-28 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField()),
                ('inspection_type', models.CharField(blank=True, max_length=80)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'N/A')], default='pass', max_length=10)),
                ('odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inspections', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='tenants.tenant')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-inspection_date', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'inspection_date'], name='inspections_tenant__30f42a_idx'), models.Index(fields=['tenant', 'vehicle'], name='inspections_tenant__12a486_idx'), models.Index(fields=['tenant', 'result'], name='inspections_tenant__022c36_idx')],
            },
        ),
    ]
