# Generated by Django 4.2.27 on 2025-12-28 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspection',
            options={'ordering': ['-inspection_date', '-created_at'], 'permissions': [('assign_inspections', 'Can assign inspections'), ('complete_inspections', 'Can complete inspections')]},
        ),
        migrations.AddField(
            model_name='inspection',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inspections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspection',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='assigned', max_length=20),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['tenant', 'status'], name='inspections_tenant__e4cc8d_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['tenant', 'assigned_to'], name='inspections_tenant__d895fb_idx'),
        ),
    ]
