# Generated by Django 4.2.27 on 2025-12-29 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspections', '0002_alter_inspection_options_inspection_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspection',
            options={'ordering': ['-inspection_date', '-created_at'], 'permissions': [('assign_inspections', 'Can assign inspections'), ('complete_inspections', 'Can complete inspections'), ('manage_inspection_alerts', 'Can manage inspection alerts')]},
        ),
        migrations.CreateModel(
            name='InspectionAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('ack', 'Acknowledged'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('title', models.CharField(max_length=140)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inspection_alerts', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_inspection_alerts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inspection_alerts', to=settings.AUTH_USER_MODEL)),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert', to='inspections.inspection')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_alerts', to='tenants.tenant')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_alerts', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='inspections_tenant__6ec8c1_idx'), models.Index(fields=['tenant', 'severity'], name='inspections_tenant__2d4ba1_idx'), models.Index(fields=['tenant', 'vehicle'], name='inspections_tenant__228a6c_idx')],
            },
        ),
    ]
