# Generated by Django 4.2.27 on 2025-12-27 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(blank=True, max_length=50)),
                ('vin', models.CharField(blank=True, max_length=50)),
                ('plate', models.CharField(blank=True, max_length=20)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('make', models.CharField(blank=True, max_length=80)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('trim', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='tenants.tenant')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
